openapi: '3.0.0'
info:
  title: DummyApp
  version: '1.1.0'
servers:
  - url: http://localhost:5000/api/dummy/v1_0
    
paths:
  /:
    get:
      operationId: home      
      responses:
        '200':
          description: OK            
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg'
components:
  schemas:
    msg:
      type: object
      properties:
          message:
            type: string
